### ISSUE TITLE
Segmentation Fault when trying to compile tcc

### ISSUE THREAD

**Issue by rain-1** [larmel/lacc#4]
Hello.

On my system I built lacc and make test and amke test-selfhost are working.

I tried `lacc tcc.c` and it got me a segmentation fault..

http://repo.or.cz/tinycc.git

**Comment by larmel** [comment]
Hi. Thank you for reporting this issue. There was an error in how include paths were constructed, which should be fixed in d5c7d09badb66349879d97a52e64c33cb8f5175d.

I see that tcc depends on some extensions that are currently not supported by lacc, such as zero-length arrays and short bitfields, so it will still not compile. I will work on adding these features.

**Comment by rain-1** [comment]
That's great to hear, thank you!
