### ISSUE TITLE
ld.lld: error: bin/bootstrap/abi.o: unsupported relocation reference

### ISSUE THREAD

**Issue by ibara** [larmel/lacc#8]
Hi --

`lacc` is unable to build itself when the linker is `lld`, the LLVM linker. When running `make bin/selfhost/lacc`, the bootstrap `lacc` builds and links fine. When the bootstrap `lacc` tries to build `lacc`, `lld` gives the complaint seen in the title of this issue report.

Both GNU `ld` and GNU `gold` happily link the selfhosted `lacc` so this seems to be something unique to `lld`.

**Comment by larmel** [comment]
This error was caused by relocation sections being placed before their targets (f.ex .rela.text before .text). Turns out lld is more pedantic than gnu linker, so I fixed some more issues as well before it stopped complaining. Should work now.

Thanks for reporting this. Using lld was very useful to validate the generated object files.
